---

- name: Install Java 11
  apt: name=openjdk-11-jdk-headless

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.8/bin/apache-tomcat-8.5.8.tar.gz dest=/opt/apache-tomcat-8.5.8.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-8.5.8.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.8

- name: Symlink install directory
  file: src=/opt/apache-tomcat-8.5.8 path=/usr/share/tomcat state=link force=yes

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: Creating a service file
  copy: 
    dest: /etc/systemd/system/tomcat.service
    content: |
        [Unit]
        Description=Tomcat Service
        Requires=network.target
        After=network.target
        [Service]
        Type=forking
        User=tomcat
        Environment="CATALINA_PID=/usr/share/tomcat/temp/tomcat.pid"
        Environment="CATALINA_BASE=/usr/share/tomcat"
        Environment="CATALINA_HOME=/usr/share/tomcat"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        ExecStart=/usr/share/tomcat/bin/startup.sh
        ExecStop=/usr/share/tomcat/bin/shutdown.sh
        User=tomcat
        Group=tomcat
        UMask=0007
        RestartSec=10
        Restart=always
        [Install]
        WantedBy=multi-user.target

- name: systemd daemon-reload
  shell: systemctl daemon-reload

- name: tomcat-8-start
  shell: systemctl start tomcat

- name: wait for tomcat to start
  wait_for: port={{http_port}}
