---
# This playbook deploys a simple standalone Tomcat 7 ot 8 with JDK 8

- hosts: slave
  become_user: root
  become: yes
  become_method: sudo

  pre_tasks:
    - debug: var=version
 # choice the tomcat version
  roles:  
    - role: apache-maven
